services:
  murkel3:
    image: ghcr.io/relativity74205/murkelhausen_app3/murkel_app3:1.8.0
    container_name: murkelhausen3
    restart: always
    ports:
      - "80:8000"
    hostname: murkel3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - DJANGO__SECRET_KEY=${DJANGO__SECRET_KEY}
      - DJANGO__DEBUG=${DJANGO__DEBUG}
      - DJANGO__ALLOWED_HOSTS=${DJANGO__ALLOWED_HOSTS}
      - PIHOLE_PRIMARY_PASSWORD=${PIHOLE_PRIMARY_PASSWORD}
      - PIHOLE_BACKUP_PASSWORD=${PIHOLE_BACKUP_PASSWORD}
#      - PODCASTINDEX_API_SECRET=${PODCASTINDEX_API_SECRET}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
      - GOOGLE_CALENDAR_ARKADIUS=${GOOGLE_CALENDAR_ARKADIUS}
      - GOOGLE_CALENDAR_FAMILIE=${GOOGLE_CALENDAR_FAMILIE}
      - GOOGLE_CALENDAR_ERIK=${GOOGLE_CALENDAR_ERIK}
      - GOOGLE_CALENDAR_MATTIS=${GOOGLE_CALENDAR_MATTIS}
      - GOOGLE_CALENDAR_ANDREA=${GOOGLE_CALENDAR_ANDREA}
      - GOOGLE_CALENDAR_GEBURTSTAGE=${GOOGLE_CALENDAR_GEBURTSTAGE}